### ISSUE TITLE
Change Time Format

### ISSUE THREAD

**Issue by RT94** [ijgnd/anki__when_is_next_learning_card_due_today_due#5]
Hi is there a way to change the time to a 12 hr clock instead of 24 hr like it currently is?

**Comment by RT94** [comment]
Thanks for the quick response. I see the new configuration option, but now the text does not appear on the main screen

**Comment by ijgnd** [comment]
have you restarted anki?

**Comment by RT94** [comment]
Yes I did

**Comment by ijgnd** [comment]
I'll look into this another time. I just reverted the ankiweb version. Thanks for testing.

**Comment by RT94** [comment]
Ok sounds good

**Comment by ijgnd** [comment]
I forgot to ask: Did you still have learning cards due today? If not nothing is shown.

**Comment by RT94** [comment]
Oh wow my bad. I didn't even think to look. Can you please add the update back then? 😂

**Comment by RT94** [comment]
I also forgot to ask, is there a way to change the text color to any color the user wants?

**Comment by ijgnd** [comment]
update again.

> I also forgot to ask, is there a way to change the text color to any color the user wants?

you should really hover all the icons on the top right of the editor and then search the add-on list for the pretty obvious term "color" or "colour".

**Comment by RT94** [comment]
Alright thanks
